### PR TITLE
Update Plots

### PR DESCRIPTION
**Pull request by lghszdnp**
Fixed the the plots for homoscedasticity.

### CODE REVIEW

**Review by Phichchaya27 — CHANGES_REQUESTED** [review]
“Recommended Priority: High”
1) There is still an open current GitHub issue left.
2) In the part of Random Effect in the Drag and Drop game if I chose only "Random effect" or 1 right assumption plus "Random effect" the message that should say "You failed to list some assumptions" is missing.
3) In the part of Normality in the Multiple Choices game, I think that the order of plot B and plot C are switched. (not sure)
4) In the part of Homoscedasticity in the Multiple Choices game, labels that state which are plot A, plot B, and plot C are missing.
5) In the part of Independence of observation the Multiple Choices game, the labels of plot should be in order A, B and C (not sure)
6) In the part of Linear in the Multiple Choices game, labels that state which are plot A, plot B, and plot C are missing.
7) In the part of Common slope in the Multiple Choices game, labels that state which are plot A, plot B, and plot C are missing.
8) In the part of No potential outliers in the Multiple Choices game, labels that state which are plot A, plot B, and plot C are missing.
9) In the part of Interaction of block in the Multiple Choices game, labels that state which are plot A, plot B, and plot C are missing.
10) There is no reference for car and lme4 P packages.

**Review by Phichchaya27 — DISMISSED** [review]

**Review by sv101 — COMMENTED** [review]
The app has a few errors. There seem to be git merge tags left throughout the code which doesn't let your app be launched. 
An example is line 2552 and 2677

**Review by NurulSyafiqah-pixel — DISMISSED** [review]
I don't see any issue to be pointed out. Can move to next step.

**Review by sv101 — DISMISSED** [review]
The app looks great. The app can move to the next step

**Comment by neilhatfield** [comment]
@Phichchaya27, @sv101, @NurulSyafiqah-pixel 
I'm dismissing the approving reviews and am going to require some additional modifications. There are some issues that I think would be good to address in this update and there are some issues that should have been caught and addressed in Peer Reviews that must be fixed.

### Must Fix Issues
- [x] Block Tab of Assumptions, lines 265-277: there is a set of order lists (with no items) inside of paragraph tags. These would be changed to a single unordered list (`tags$ul`) with five items (i.e., five `tags$li` calls).
- [x] Please come up with better names than `game1` and `game2`; I know you inherited these from past students. This also has a secondary question of potentially improving the names that appear in the left-hand menu.
- [x] I'm unsure why the scoring icons in both games have gone from the correct style to a much older style. These should be using the `renderIcon` function, and disappear when the user changes an answer.
- [ ] The console gets messages printed to it. For example "`geom_smooth()` using formula 'y ~ x'" and "boundary (singular) fit: see help('isSingular')". These need to be investigate and resolved.

### Additional Changes
- Please add more structure to the code; you do this by adding `----` after a comment which will become a label
- Double check code formatting
- Remove extra colons (see post in Teams)
- Move the aria-label text to the `alt` argument of the `renderPlot` (This app was first created before this argument got added.)
- There is a lot of redundant coding in this app; we need to take care of some of it now
  - Create a constant that is the list of assumptions for first game in the second section of the app. Then you can just call this object instead of the long list each time.
  - For the first game, ditch the tabs entirely. For now, use a `selectInput` to toggle between what the valid answers are.
  - Since you've fixed the sidebar, we need to take a new screenshot.

**Comment by Phichchaya27** [comment]
Remaining issues
- [ ] The console gets messages printed to it. For example "geom_smooth() using formula 'y ~ x'" and "boundary (singular) fit: see help('isSingular')". These need to be investigate and resolved.
- [ ] Move the aria-label text to the alt argument of the renderPlot (This app was first created before this argument got added.)
- [ ] For the first game, ditch the tabs entirely. For now, use a selectInput to toggle between what the valid answers are.

**Review by Sburke26 — CHANGES_REQUESTED** [review]
Here are some things I noticed when reviewing:

The README.html file is probably not needed, as we have the README.md.
The descriptions file is missing the heading of "App Description".
The year badge does not appear to be updated.
In the instructions, maybe use "examine" instead of "exam".
The button on the Overview page should probably be labelled according to where it goes.
When loading the "No Statistically Significant Potential Outliers" Plot in the ANCOVA section, there is an error: "object 'keyboarding' not found". 
The alt argument has not been updated yet.
There is a bug in the Assumption Checking where there does not appear to be a right answer. 
There is also no feedback that appears with incorrect answers in this Assumption Checking Quiz. 
The console message `geom_smooth()` using formula = 'y ~ x' is also still present.

**Comment by luqije** [comment]
- In the console, appears to have a warning message about "Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0".
- On the Overview page, the "Cite the app as:" is missing and the Last update year needs to change. 
- On the Prerequisites page, maybe add different methods of ANOVA under the section "What is ANOVA?" as shown in the Explore page with additional definitions.  
- On the Explore page, add an explanation of what the dashed areas mean in the plots. 
- No alt on each plot. Also, in Multiple Choice Game, no feedback on incorrect answers.
- On the Reference page, missing references for the car and lme4 packages.

**Review by luqije — CHANGES_REQUESTED** [review]
- In the console, appears to have a warning message about "Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0".
- On the Overview page, the "Cite the app as:" is missing and the Last update year needs to change. 
- On the Prerequisites page, maybe add different methods of ANOVA under the section "What is ANOVA?" as shown in the Explore page with additional definitions.  
- On the Explore page, add an explanation of what the dashed areas mean in the plots. 
- No alt on each plot. Also, in Multiple Choice Game, no feedback on incorrect answers.
- On the Reference page, missing references for the car and lme4 packages.

**Review by Sburke26 — CHANGES_REQUESTED** [review]
Here are something I noticed needed fixing:

The year badge in the README does not match the year in the description.
The authors section of the description does not match the acknowledgements in the Overview. (Don't forget to add yourself too).
I still found console messages while using the app for the use of size instead of linewidth and geom_smooth using y ~ x. (Make sure all geom_smooth or smooth functions have a formula argument to avoid the y ~x message).
There are a lot of lines with a blue i in r that signify that there are spacing issues.
The Assumption Checking page does not appear to have any correct answers .( I looked and saw the object names are not consistent for the mcq answers between the server and UI).
You can also delete the cross and check images in the www folder as they are outdated symbols.

**Comment by luqije** [comment]
Thank you, Sean. I fixed the issues that you mentioned. Please let me know if I missed anything.

**Review by Sburke26 — CHANGES_REQUESTED** [review]
Good work with the updates. I only noticed a couple of things:

I saw that there are a couple of warnings on lines 1857, 1756, 1666, and 1579 for missing arguments. It may be necessary to add default arguments to fix the issue. 

I noticed there was still a message about using linewidth instead of size. I think it may have been caused by a geom_line() function in one of the plots. 

This is not a functionality issue, but I would recommend looking into what plots you can convert to ggplot to maintain a similar style among the plots.

**Pull request merged**
